name: Build and deploy PHP app to Azure Web App - tour

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Adjust PHP version if needed

      - name: Move files to the root
        run: |
          mv src/* .
          rm -rf src

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tour'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}

